# Please edit this configuration file to match your environment (on Windows).
# Examples in comments below - check/change the paths.
logger:
  type: file
  level: debug   # Set to debug for better visibility
  truncate_tools: true
  
# Default Model Configuration:
default_model: openai.gpt-4.1-nano

mcp:
  servers:
    filesystem:
      # On windows update the command and arguments to use `node` and the absolute path to the server.
      # Use `npm i -g @modelcontextprotocol/server-filesystem` to install the server globally.
      # Use `npm -g root` to find the global node_modules path.`
      # command: "node"
      # args: ["c:/Program Files/nodejs/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js","."]
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    
    # ============================================================================
    # MCPO Endpoint Configuration
    # ============================================================================
    # 
    # MCPO endpoints are RESTful HTTP proxies to individual MCP tools.
    # To use these with Fast-Agent, uncomment the configurations below
    # and make sure MCPO is running (e.g., via `npm install -g mcpo && mcpo server`).
    #
    # To use these tools in your code:
    #
    # await context.executor.call_tool(
    #   "get_current_time",    # The actual tool method name (from MCPO docs)
    #   {"timezone": "UTC"},   # Parameters for the tool
    #   server="mcpo-time"     # The server name from this config
    # )
    
    # MCPO Time endpoint - provides time tools (get_current_time, convert_time)
    mcpo-time:
      transport: "streamable_http"
      url: "http://localhost:8000/time"
    
    # MCPO Fetch endpoint - HTTP fetching tool
    mcpo-fetch:
      transport: "streamable_http"
      url: "http://localhost:8000/fetch"
    
    # Other available MCPO endpoints
    # mcpo-arxiv:
    #   transport: "streamable_http"
    #   url: "http://localhost:8000/arxiv-latex"
    #
    # mcpo-serena:
    #   transport: "streamable_http"
    #   url: "http://localhost:8000/serena"