$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  path: "./mcp_agent.log"
  progress_display: false

mcp:
  servers:
    mcp_root:
      type: "mcp_root"
      command: "uv"
      args: ["run", "../mcp_root_test/root_test_server.py"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
